<a href="https://colab.research.google.com/github/RonitARK/davis_training/blob/main/classwork/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
data = np.array([45,"python",69])
print(data)

['45' 'python' '69']


In [3]:
import numpy as np
numbers = np.array([45,101,69])
print(numbers)

[ 45 101  69]


In [4]:
import numpy as np
numbers = np.array([45.5,101.0,69.69])
print(numbers)

[ 45.5  101.    69.69]


In [6]:
array4 = np.zeros((4,5),dtype=int)
print(array4)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [7]:
array4 = np.zeros((3,6,2),dtype=int)
print(array4)

[[[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]]


In [8]:
array4 = np.ones((2,1,3),dtype=int)
print(array4)

[[[1 1 1]]

 [[1 1 1]]]


In [13]:
array4 = np.full((69,69,69), 69, dtype=int)
print(array4)

[[[69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  ...
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]]

 [[69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  ...
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]]

 [[69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  ...
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]]

 ...

 [[69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  ...
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]]

 [[69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  ...
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]]

 [[69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  ...
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]
  [69 69 69 ... 69 69 69]]]


In [18]:
import numpy as np

def get_even_factors_simple(num):
    even_factors = []
    if num == 0:
        return even_factors # Zero has no even factors in this context

    # Get factors for the absolute value of the number
    abs_num = abs(num)
    for i in range(1, abs_num + 1):
        if abs_num % i == 0 and i % 2 == 0:
            even_factors.append(i)
    return even_factors

# Test with different types of numbers
numbers_to_test = [24, -8, 0, 15, 100, -50]

for number_to_check in numbers_to_test:
    even_factors_list = get_even_factors_simple(number_to_check)

    if even_factors_list:
        even_factors_array = np.array(even_factors_list)
        print(f"The even factors of {number_to_check} are: {even_factors_array}")
    elif number_to_check == 0:
        print(f"Zero has no even factors.")
    else:
        print(f"There are no even factors for {number_to_check} (or all factors are odd).")

The even factors of 24 are: [ 2  4  6  8 12 24]
The even factors of -8 are: [2 4 8]
Zero has no even factors.
There are no even factors for 15 (or all factors are odd).
The even factors of 100 are: [  2   4  10  20  50 100]
The even factors of -50 are: [ 2 10 50]
